# Generated by Django 5.2.8 on 2025-11-15 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_managers_remove_user_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Автоматически генерируется из первого сообщения', max_length=255, verbose_name='Заголовок')),
                ('category', models.CharField(choices=[('general', 'Общее'), ('legal', 'Юридическая консультация'), ('marketing', 'Маркетинг'), ('finance', 'Финансы'), ('hr', 'Управление персоналом'), ('operations', 'Операционные вопросы')], default='general', max_length=50, verbose_name='Категория')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('archived', 'Архивирован'), ('completed', 'Завершен')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Время последнего сообщения в диалоге', null=True, verbose_name='Последнее сообщение')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительная информация о диалоге', verbose_name='Метаданные')),
                ('business', models.ForeignKey(blank=True, help_text='Бизнес, для которого ведется диалог (опционально)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.business', verbose_name='Бизнес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент'), ('system', 'Система')], max_length=20, verbose_name='Роль')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('model', models.CharField(blank=True, help_text='Название модели LLM, использованной для генерации ответа', max_length=100, verbose_name='Модель LLM')),
                ('tokens_used', models.IntegerField(blank=True, help_text='Количество токенов использованных для генерации ответа', null=True, verbose_name='Использовано токенов')),
                ('response_time', models.FloatField(blank=True, help_text='Время генерации ответа в секундах', null=True, verbose_name='Время ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительная информация о сообщении (промпт, параметры и т.д.)', verbose_name='Метаданные')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='Диалог')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='chat_conver_last_me_31163c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'status'], name='chat_conver_user_id_f98e31_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['business', 'status'], name='chat_conver_busines_b1205e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role'], name='chat_messag_role_9cd150_idx'),
        ),
    ]
