# Generated by Django 5.2.8 on 2025-11-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='completed', help_text='Статус обработки сообщения AI (для асинхронных запросов)', max_length=20, verbose_name='Статус обработки'),
        ),
    ]
