# Generated by Django 5.2.8 on 2025-11-15 09:39

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Используется для входа в систему', max_length=254, unique=True, verbose_name='Email адрес')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Username')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('business_type', models.CharField(choices=[('cafe', 'Кафе/Кофейня'), ('restaurant', 'Ресторан'), ('beauty_salon', 'Салон красоты'), ('barbershop', 'Барбершоп'), ('retail', 'Магазин'), ('fitness', 'Фитнес/Спорт'), ('services', 'Услуги'), ('other', 'Другое')], max_length=50, verbose_name='Тип бизнеса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('archived', 'Архивирован')], default='active', max_length=20, verbose_name='Статус')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Бизнес',
                'verbose_name_plural': 'Бизнесы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees_count', models.IntegerField(default=1, verbose_name='Количество сотрудников')),
                ('business_context', models.TextField(blank=True, help_text='Дополнительная информация для AI ассистента', verbose_name='Контекст бизнеса')),
                ('ai_preferences', models.JSONField(blank=True, default=dict, help_text='Предпочтения для работы AI ассистента', verbose_name='Настройки AI')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.business', verbose_name='Бизнес')),
            ],
            options={
                'verbose_name': 'Профиль бизнеса',
                'verbose_name_plural': 'Профили бизнесов',
            },
        ),
        migrations.CreateModel(
            name='BusinessMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('period_type', models.CharField(choices=[('day', 'День'), ('week', 'Неделя'), ('month', 'Месяц')], default='day', max_length=20, verbose_name='Тип периода')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выручка')),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Расходы')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Прибыль')),
                ('customers_count', models.IntegerField(default=0, verbose_name='Количество клиентов')),
                ('transactions_count', models.IntegerField(default=0, verbose_name='Количество транзакций')),
                ('avg_check', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Средний чек')),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Специфичные для отрасли метрики', verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='users.business', verbose_name='Бизнес')),
            ],
            options={
                'verbose_name': 'Метрика бизнеса',
                'verbose_name_plural': 'Метрики бизнеса',
                'ordering': ['-date'],
                'unique_together': {('business', 'date', 'period_type')},
            },
        ),
    ]
